import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";

export interface ExtensionArtifact {
  category: "override" | "extension" | "new" | "hook" | "foreign";
  name: string;
  target: string;
  /** Who wrote the content, for a `foreign` artifact the maestro moved but never owns (SPEC-0024, FR-004). */
  origin?: string;
  /** The content generated by the CLI, between the anchors — it's what repair restores; the checksum alone doesn't allow reconstruction. */
  content: string;
  checksum: string;
  createdAt: string;
}

export interface ExtensionRegistry {
  artifacts: ExtensionArtifact[];
}

/**
 * Read/write source, injected in the same pattern as
 * `RegistryEnvironment` (fatia 1i, `src/approval/registry.ts`) — the
 * suite never depends on the disk of whoever runs it.
 */
export interface ChecksumEnvironment {
  read(): string;
  write(contents: string): void;
}

export const REGISTRY_PATH = ".maestro/extensions.json";

export function realChecksumEnvironment(root: string): ChecksumEnvironment {
  const path = join(root, REGISTRY_PATH);
  return {
    read: () => (existsSync(path) ? readFileSync(path, "utf8") : ""),
    write: (contents: string) => {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, contents);
    },
  };
}

/** Missing, empty, or invalid JSON resolves to an empty registry — never throws. */
export function readExtensionRegistry(env: ChecksumEnvironment): ExtensionRegistry {
  const raw = env.read().trim();
  if (raw.length === 0) return { artifacts: [] };
  try {
    const value = JSON.parse(raw) as unknown;
    if (typeof value !== "object" || value === null || !Array.isArray((value as ExtensionRegistry).artifacts)) {
      return { artifacts: [] };
    }
    return { artifacts: (value as ExtensionRegistry).artifacts };
  } catch {
    return { artifacts: [] };
  }
}

export function writeExtensionRegistry(registry: ExtensionRegistry, env: ChecksumEnvironment): void {
  env.write(JSON.stringify(registry, null, 2));
}
